config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  unauthenticated do
    root to: 'static#index'
  end

  authenticated do
    root to: 'logs#index'
  end

  resources :static, only: [:index]
  resources :recipes
  resources :foods do
    get 'search', on: :collection
  end


  resources :users, only: [] do
    resources :logs do
      get 'today', on: :collection
    end
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, optional: true

  has_many :ingredients
  has_many :recipes, through: :ingredients

  validates :food_name, :serving_unit, presence: true
  validates :unique_name, uniqueness: { conditions: -> { from_api } }

  validates :unique_name,
            uniqueness: {
              scope: :user_id,
              conditions: -> { from_user }
            }

  validates :serving_qty,
            :calories,
            :total_fat,
            :total_carbohydrate,
            :protein,
            numericality: { greater_than_or_equal_to: 0 }

  validates :saturated_fat,
            :serving_weight_grams,
            :cholesterol,
            :sodium,
            :dietary_fiber,
            :sugars,
            :potassium,
            :ndb_no,
            :tag_id,
            numericality: { greater_than_or_equal_to: 0, allow_nil: true }

  validate :user_foods_have_user_id
  validate :api_food_does_not_have_user_id

  before_validation :set_unique_name

  # Validation Method
  def user_foods_have_user_id
    return unless ndb_no.blank? && user_id.blank?

    errors.add(:user_id, 'created foods must have user_id')
  end

  # Validation Method
  def api_food_does_not_have_user_id
    return unless user_id.present? && ndb_no.present?

    errors.add(:user_id, 'cannot create api foods')
  end

  def food_name=(name)
    super(name.titleize) if name
  end

  def serving_unit=(unit)
    super(unit.titleize) if unit
  end

  def from_api?
    ndb_no.present?
  end

  class << self
    def from_api
      where.not(ndb_no: nil)
    end

    def from_user
      where(ndb_no: nil)
    end

    def find_or_create_from_api(foods)
      foods.collect do |food|
        new_food = Food.create(food)

        if new_food.invalid?
          find_by(unique_name: new_food.unique_name)
        else
          new_food
        end
      end
    end
  end

  private

  def set_unique_name
    self.unique_name = "#{food_name} - #{serving_qty} - #{serving_unit}"
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  after_action :verify_authorized, except: [:index, :search, :new, :create]
  after_action :verify_policy_scoped, only: [:index]

  def search
    api = NutritionIx.new(params[:query])
    foods = Food.find_or_create_from_api(api.foods)

    unless api.errors?
      serializer = ActiveModelSerializers::SerializableResource
      foods_for_select = policy_scope(Food).order(unique_name: :asc)

      render json: {
        foods: serializer.new(foods).as_json,
        select: serializer.new(foods_for_select).as_json
      }, status: 200
    else
      render json: {error: I18n.t('food.search.error')}, status: 400
    end
  end

  def index
    case params[:sort]
    when "desc"
      @foods = policy_scope(Food).order(unique_name: :desc)
    else
      @foods = policy_scope(Food).order(unique_name: :asc)
    end

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @foods }
    end
  end

  def show
    @food = Food.find(params[:id])
    authorize @food
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.create(food_params)

    if @food.valid?
      redirect_to food_path(@food)
    else
      render :new
    end
  end

  def edit
    @food = Food.find(params[:id])
    authorize @food
  end

  def update
    @food = Food.find(params[:id])
    authorize @food

    @food.update(food_params)

    if @food.save
      redirect_to food_path(@food)
    else
      render :edit
    end
  end

  def destroy
    @food = Food.find(params[:id])
    authorize @food

    if @food.destroy
      redirect_to foods_path, notice: "#{@food.unique_name} was deleted."
    else
      redirect_to food_path(@food),
                  alert: "#{food.unique_name} could not be deleted."
    end
  end

  private

  def food_params
    params.require(:food).permit(
      :food_name,
      :serving_qty,
      :serving_unit,
      :calories,
      :total_fat,
      :total_carbohydrate,
      :protein
    )
  end
end

app/views/foods/_food_fields.html.erb
<div class='food-details'>
  <%= f.label :food_name, 'Name' %>
  <%= f.text_field :food_name %>

  <%= f.label :serving_qty %>
  <%= f.number_field :serving_qty, min: 0.00, step: 0.25 %>

  <%= f.label :serving_unit %>
  <%= f.text_field :serving_unit %>

  <%= f.label :calories %>
  <%= f.number_field :calories, min: 0, step: 1 %>
</div>

<div class='food-details'>
  <%= f.label :total_fat %>
  <%= f.number_field :total_fat, min: 0, step: 1 %>

  <%= f.label :total_carbohydrate %>
  <%= f.number_field :total_carbohydrate, min: 0, step: 1 %>

  <%= f.label :protein %>
  <%= f.number_field :protein, min: 0, step: 1 %>
</div>

app/views/foods/_foods.html.erb
<div class="food"><%= link_to foods.unique_name, food_path(foods) %></div>

app/views/foods/_form.html.erb
<%= form_for @food do |f| %>
  <%= render partial: 'layouts/form_errors', locals: { form_errors: @food } %>

  <div class='food-fields'>
    <%= render 'food_fields', f: f %>
  </div>

  <%= f.submit %>
<% end %>

app/views/foods/edit.html.erb
<h1>Edit Food</h1>

<%= render 'form' %>

app/views/foods/index.html.erb
<h1>Foods</h1>

<p><%= link_to 'Create a New Food', new_food_path %></p>

<p>
  Sort Foods: 
  <%= link_to 'Ascending', foods_path(sort: "asc"), class: "foods-sort" %> |
  <%= link_to 'Descending', foods_path(sort: "desc"), class: "foods-sort" %>
</p>

<div id="foods-index">
  <%= render partial: 'foods', collection: @foods || 'No foods are available.' %>
</div>

app/views/foods/new.html.erb
<h1>Add New Food</h1>

<%= render 'form' %>

app/views/foods/show.html.erb
<h1><%= @food.unique_name %></h1>

<p><%= link_to 'Edit Food', edit_food_path(@food) if policy(@food).edit? %>
<p><%= link_to 'Destroy Food', food_path(@food), method: :delete,
  data: { confirm: 'Are you sure?' } if policy(@food).destroy? %></p>

<ul>
  <li>Serving Quantity: <%= num @food.serving_qty %></li>
  <li>Serving Unit: <%= num @food.serving_unit %></li>
  <li>Calories: <%= num @food.calories %></li>
  <li>Total Fat: <%= num @food.total_fat %></li>
  <li>Total Carbohydrate: <%= num @food.total_carbohydrate %></li>
  <li>Total Protein: <%= num @food.protein %></li>
</ul>