config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  unauthenticated do
    root to: 'static#index'
  end

  authenticated do
    root to: 'logs#index'
  end

  resources :static, only: [:index]
  resources :recipes
  resources :foods do
    get 'search', on: :collection
  end


  resources :users, only: [] do
    resources :logs do
      get 'today', on: :collection
    end
  end
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user

  has_many :entries, inverse_of: :log
  has_many :recipes, through: :entries
  has_many :foods, through: :recipes
  has_many :logs_stats

  accepts_nested_attributes_for :entries, allow_destroy: true

  validates :entries, :log_date, presence: true
  validates :log_date, uniqueness: true

  def total_stats_for_chart
    {
      "Carbs": total_stats.total_carbs,
      "Protein": total_stats.total_protein,
      "Fat": total_stats.total_fat,
    }
  end

  def total_stats
    @total_stats ||= logs_stats.per_log.first
  end

  def per_recipe_stats
    @per_recipe_stats ||= logs_stats
  end

  def next(user)
    ids = user_logs_ids_by_date_asc(user)
    index = ids.find_index(id)

    if ids[index + 1]
      ids[index + 1]
    else
      nil
    end
  end

  def prev(user)
    ids = user_logs_ids_by_date_asc(user)
    index = ids.find_index(id)

    if index == 0
      nil
    else
      ids[index - 1]
    end
  end

  class << self
    def daily_carb_data(user)
      where(user_id: user.id).order(log_date: :asc).limit(14).map do |log|
        [log.log_date.strftime('%B %e, %Y'), log.total_stats.total_carbs]
      end
    end
  end

  private

  def user_logs_ids_by_date_asc(user)
    @related_logs_ids ||= user.logs.order(log_date: :asc).pluck(:id)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!

  after_action :verify_authorized, except: [:index, :new, :create]
  after_action :verify_policy_scoped, only: :index

  def index
    @logs = policy_scope(Log).order(log_date: :desc)
    @log_data = policy_scope(Log).daily_carb_data(current_user)
  end

  def show
    @log = Log.find(params[:id])
    @recipes = policy_scope(Recipe)
    authorize @log

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @log, user: current_user }
    end
  end

  def today
    @log = current_user
           .logs.find_or_initialize_by(log_date: Time.current.to_date)
    @recipes = policy_scope(Recipe)
    authorize @log

    render :new
  end

  def new
    @log = current_user.logs.new
    @recipes = policy_scope(Recipe)
  end

  def create
    @log = current_user.logs.find_or_create_by(id: params[:id])
    @log.update(log_params)
    @log.save

    if @log.valid?
      redirect_to user_log_path(current_user, @log)
    else
      render :new
    end
  end

  def edit
    @log = current_user.logs.find(params[:id])
    @recipes = policy_scope(Recipe)
    authorize @log
  end

  def update
    @log = current_user.logs.includes(:entries).find(params[:id])
    authorize @log

    @log.update(log_params)
    if @log.save
      respond_to do |format|
        format.html { redirect_to user_log_path(current_user, @log) }
        format.json { render json: @log, user: current_user }
      end
    else
      @recipes = policy_scope(Recipe)
      render :edit
    end
  end

  def destroy
    @log = Log.find(params[:id])
    authorize @log

    if @log.destroy
      redirect_to user_logs_path, notice: 'Your log was deleted.'
    else
      redirect_to user_log_paht(@log),
                  alert: 'Your log could not be deleted.'
    end
  end

  private

  def log_params
    params.require(:log).permit(
      :log_date, entries_attributes: [
        :id, :quantity, :recipe_id, :category, :_destroy
      ]
    )
  end
end

app/views/logs/_entry_fields.html.erb
<div class='nested-fields inline-fields'>
  <%= f.label :quantity %>
  <%= f.number_field :quantity, min: 0.00, step: 0.25 %>

  <%= f.label :recipe_id, 'Recipe' %>
  <%= f.collection_select :recipe_id, @recipes, :id, :title, prompt: true %>

  <%= f.label :category %>
  <%= f.collection_select :category, Entry.categories, :first, :first %>

  <%= link_to_remove_association f do %>
    <button>Remove Entry</button>
  <% end %>
</div>

app/views/logs/_form.html.erb
<%= form_for [@current_user, @log] do |f| %>
  <%= render partial: "layouts/form_errors", locals: { form_errors: @log } %>

  <%= f.hidden_field :id, value: "#{@log.id}" %>

  <% if action_name == "today" %>
    <h1>Today's Food Log for <%= date @log.log_date %> </h1>
    <%= f.hidden_field :log_date, value: "#{@log.log_date}" %>
  <% else %>
    <%= f.label :log_date %>
    <%= f.date_select :log_date, order: [:month, :day, :year] %>
  <% end %>

  <div id="entries">
    <%= f.fields_for :entries do |entries| %>
      <%= render "entry_fields", f: entries %>
    <% end %>

    <div class="links add-entry">
      <%= link_to_add_association f, :entries, {"data-association-insertion-method": "before"}  do %>
        <button>Add Entry</button>
      <% end %>
    </div>
  </div>

  <%= f.submit %>
<% end %>

app/views/logs/_logs.html.erb
<div class='log-index'>
  <div>
    <h3><%= date(logs.log_date) %></h3>
  </div>

  <div class='stats'>
    <ul>
      <li><%= num logs.total_stats.total_calories %><span>Calories</span></li>
      <li><%= num logs.total_stats.total_carbs %><span>Carbs</span></li>
      <li><%= num logs.total_stats.total_protein %><span>Protein</span></li>
      <li><%= num logs.total_stats.total_fat %><span>Total Fat</span></li>
    </ul>
  </div>

  <div>
    <p>
    <%= link_to 'View Log', user_log_path(current_user, logs) %> | 
    <%= link_to 'Edit Log', edit_user_log_path(current_user, logs) %>
    </p>
  </div>
</div>

app/views/logs/_stats.html.erb
<tr>
  <td><%= stats.title %> - <%= stats.category %></td>
  <td class='data'><%= num stats.calories %></td>
  <td class='data'><%= num stats.carbs %></td>
  <td class='data'><%= num stats.protein %></td>
  <td class='data'><%= num stats.fat %></td>
</tr>

app/views/logs/edit.html.erb
<h1>Edit Log</h1>

<%= render "form" %>

app/views/logs/index.html.erb
<h1>Food Logs</h1>

<div class="chart">
  <%# <%= column_chart @log_data if @log_data.present? %1> %>
  <% if @log_data.present? %>
    <%= column_chart @log_data %>
  <% else %>
    <p>You haven't logged any foods.  Why not start today!
    <%= link_to "Log Foods for Today", today_user_logs_path(current_user) %></p>
  <% end %>
</div>

<%= render partial: 'logs', collection: @logs %>

app/views/logs/new.html.erb
<h1>Create New Log</h1>

<%= render "form" %>

app/views/logs/show.html.erb
<h1 id="log-show-date">Log Date: <%= date(@log.log_date) %></h1>

<div id="log-show-nav">
  <div id="log-show-manage">
    <p>
    <%= link_to 'Edit Log', edit_user_log_path(current_user, @log) \
      if policy(@log).edit? %>
    </p>

    <p>
    <%= link_to 'Delete Log', user_log_path(current_user, @log), method: :delete,
      data: { confirm: 'Are you sure?' } if policy(@log).destroy? %>
    </p>
  </div>

  <div id="log-history">
    <p id="prev-log">
    <% if @log.prev(current_user) %>
      <%= link_to "Previous Log", 
        user_log_path(current_user, 
        @log.prev(current_user)) %>
    <% end %>
    </p>
    <p id="next-log">
    <% if @log.next(current_user) %>
      <%= link_to "Next Log", 
        user_log_path(current_user, 
        @log.next(current_user)) %>
    <% end %>
    </p>
  </div>
</div>

<div id="log-show-chart">
  <h2>Macronutrients</h2>
  <%= pie_chart @log.total_stats_for_chart %>
</div>

<div id="log-show-form">
  <h2>Add a New Log Entry</h2>
  <%= form_for [@current_user, @log] do |f| %>
    <div class='inline-fields'>
      <%= f.fields_for :entries, @log.entries.build do |entries| %>
        <%= entries.label :quantity %>
        <%= entries.number_field :quantity, min: 0.00, step: 0.25 %>

        <%= entries.label :recipe_id, 'Recipe' %>
        <%= entries.collection_select :recipe_id, @recipes, :id, :title, prompt: true %>

        <%= entries.label :category %>
        <%= entries.collection_select :category, Entry.categories, :first, :first %>
      <% end %>
      <%= f.submit "Add Entry" %>
    </div>
  <% end %>
</div>

<div id="log-show-data">
  <h2>Total Nutrition as Logged</h2>
  <table class='tables recipe'>
    <thead>
      <tr>
        <th>Recipe</th>
        <th>Calories</th>
        <th>Carbohydrate</th>
        <th>Protein</th>
        <th>Fat</th>
      </tr>
    </thead>
    <tbody id="log-show-stats-table-body">
      <%= render partial: 'stats', collection: @log.per_recipe_stats %>
      <tr class='total'>
        <td>Day's Total</td>
        <td class='data'><%= num @log.total_stats.total_calories %></td>
        <td class='data'><%= num @log.total_stats.total_carbs %></td>
        <td class='data'><%= num @log.total_stats.total_protein %></td>
        <td class='data'><%= num @log.total_stats.total_fat %></td>
      </tr>
    </tbody>
  </table>
</div>