config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  unauthenticated do
    root to: 'static#index'
  end

  authenticated do
    root to: 'logs#index'
  end

  resources :static, only: [:index]
  resources :recipes
  resources :foods do
    get 'search', on: :collection
  end


  resources :users, only: [] do
    resources :logs do
      get 'today', on: :collection
    end
  end
end

app/views/layouts/_debug.html.erb
<% if Rails.env.development? %>
  <section><%= debug(params) %></section>
<% end %>

app/views/layouts/_flashes.html.erb
<section class="flash">
  <% flash.each do |key, value| %>
    <div class="flash-<%= key.to_s %>">
      <span><%= value %></span>
    </div>
  <% end %>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer-2" role="contentinfo">
  <main>
    <ul>
      <li>Carb Tracker</li>
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Food Log", user_logs_path(current_user) %></li>
        <li><%= link_to "Recipes", recipes_path %></li>
        <li><%= link_to "Foods", foods_path %></li>
      <% end %>
    </ul>

    <div class="footer-secondary-links">
      <ul>
        <li>Made in PA, U.S.A.</li>
        <li>&copy 2016 <%= link_to "Scott Savage", "https://www.savage.com" %></li>
      </ul>
    </div>
  </main>
</footer>

app/views/layouts/_form_errors.html.erb
<% if form_errors.errors.any? %>
  <div id="error_explanation">
    <h3>Your form couldn't be processed because of the follow errors:</h3>
    <ul>
      <% form_errors.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="centered-navigation" role="banner">
  <div class="centered-navigation-wrapper">
    <%= link_to root_path, class: "mobile-logo" do %>
      <%= image_tag "logo.png", alt: t("title") %>
    <% end %>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
        <li class="nav-link"><%= link_to "Carb Tracker", static_index_path %></li>

        <% if user_signed_in? %>
          <li id="js-centered-more" class="nav-link more">
            <%= link_to t("nav.log.logs"), user_logs_path(current_user) %>
            <ul class="submenu">
              <li>
                <%= link_to t("nav.log.today"), today_user_logs_path(current_user) %>
              </li>
              <li>
                <%= link_to t("nav.log.new"), new_user_log_path(current_user) %>
              </li>
            </ul>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <li id="js-centered-more" class="nav-link more">
            <%= link_to t("nav.recipes.recipes"), recipes_path %>
            <ul class="submenu">
              <li><%= link_to t("nav.recipes.new"), new_recipe_path %></li>
            </ul>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <li id="js-centered-more" class="nav-link more">
            <%= link_to t("nav.foods.foods"), foods_path %>
            <ul class="submenu">
              <li><%= link_to t("nav.foods.new"), new_food_path %></li>
            </ul>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <li id="js-centered-more" class="nav-link more">
            <%= link_to current_user.email, user_logs_path(current_user) %>
            <ul class="submenu">
              <li>
                <%= link_to t("nav.users.account"),
                  edit_user_registration_path(current_user) %>
              </li>
              <li>
                <%= link_to t("nav.users.signout"),
                  destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-link">
            <%= link_to t("nav.users.signin"), new_user_session_path %>
          </li>
          <li class="nav-link">
            <%= link_to t("nav.users.signup"), new_user_registration_path %>
          </li>
        <% end %>

        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carb Tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag params[:controller] if params[:controller] == 'static' %>
    <%= javascript_include_tag 'application' %>
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
  </head>

  <body>
    <div class="wrapper-for-content-outside-of-footer">
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/flashes' %>

      <main><%= yield %></main>

      <%= render 'layouts/debug' %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>